language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
    - SYMFONY_VERSION=~2.1.0
    - SYMFONY_VERSION=~2.2.0
    - SYMFONY_VERSION=~2.3.0
    - SYMFONY_VERSION=dev-master

matrix:
    allow_failures:
        - env: SYMFONY_VERSION=dev-master

before_script:
    - composer self-update
    - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
    - composer update

script: phpunit --coverage-text
