language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
    include:
        - php: 5.5
          env: SYMFONY_VERSION='2.1.*'
        - php: 5.5
          env: SYMFONY_VERSION='2.2.*'
        - php: 5.5
          env: SYMFONY_VERSION='2.3.*'
        - php: 5.5
          env: SYMFONY_VERSION='2.4.*'
        - php: 5.5
          env: SYMFONY_VERSION='dev-master'
    allow_failures:
        - env: SYMFONY_VERSION=dev-master

before_script:
    - composer self-update
    - sh -c 'if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony=$SYMFONY_VERSION; fi;'
    - composer install

script: phpunit --coverage-text
